'use client'

import { ReactElement } from 'react'
import HeadLine from '../HeadLine'
import { useLanguage } from '../../contexts/LanguageContext'

const texts = {
  ja: {
    title: 'ニュース・リンク',
    description: '弊社事業に関連するリンクや情報をご紹介いたします',
    externalLink: '外部リンク',
    entries: [
      {
        title: 'MyniQ',
        url: 'https://daily-ai-generated-quiz.deno.dev/?from=corp',
        description:
          'AIが生成する英語の短文と読解力テストが毎日出題されます。代表がLLMの習作として作成したサービスです',
      },
      {
        title: '暮らし',
        url: 'https://www.instagram.com/ayhouse_jp/',
        description:
          'シェアハウスの暮らしの様子や、入居者の活動の様子を発信しています。※このアカウントは居住者により運営されており、掲載される情報は弊社の公式見解と異なる場合があります',
      },
      {
        title: 'イベント',
        url: 'https://lu.ma/calendar/cal-Zw1RO86DAlUqrRv',
        description:
          'オープンハウスなど、シェアハウスで開催されるイベントの案内と参加申し込みができます。居住者も参加可能なイベントを随時公開しています',
      },
    ],
  },
  en: {
    title: 'News & Links',
    description: 'Links and information related to our business',
    externalLink: 'External Link',
    entries: [
      {
        title: 'MyniQ',
        url: 'https://daily-ai-generated-quiz.deno.dev/?from=corp',
        description:
          'Daily English short sentences and comprehension tests generated by AI. A service created by our CEO as a practice project using LLM',
      },
      {
        title: 'Life',
        url: 'https://www.instagram.com/ayhouse_jp/',
        description:
          'Updates about daily life and activities of residents at our share house. Note: This account is managed by residents, and the information provided may differ from our official statements',
      },
      {
        title: 'Events',
        url: 'https://lu.ma/calendar/cal-Zw1RO86DAlUqrRv',
        description:
          'Information and registration for events at our share house, including open house events. We regularly publish events that are open to both residents and visitors',
      },
    ],
  },
}

export default function Other(): ReactElement {
  const { lang } = useLanguage()
  const t = texts[lang]

  return (
    <>
      <HeadLine id="other">{t.title}</HeadLine>
      <div className="mt-10 mx-auto">
        <p>{t.description}</p>
      </div>
      <div className="mt-10 mx-auto">
        <ul className="pl-2">
          {t.entries.map((entry, index) => (
            <a key={index} href={entry.url} target={'_blank'}>
              <dl className="flex flex-row">
                <dt className="text-lg w-24 min-w-[6rem] flex-shrink-0">
                  {entry.title}
                </dt>
                <dd className="px-2 flex-1">
                  <p className="underline">
                    {entry.url}
                    <span
                      title={t.externalLink}
                      className="inline-block align-sub bg-[url(/img/icons/link.svg)] bg-no-repeat w-3 h-3 ml-1"
                    />
                  </p>
                  <p className="mt-2">{entry.description}</p>
                </dd>
              </dl>
            </a>
          ))}
        </ul>
      </div>
    </>
  )
}
