'use client'

import { ReactElement } from 'react'
import HeadLine from '../HeadLine'
import { useLanguage } from '../../contexts/LanguageContext'

const texts = {
  ja: {
    title: 'ニュース・リンク',
    description: '弊社事業に関連するリンクや情報をご紹介いたします',
    externalLink: '外部リンク',
    entries: [
      {
        title: 'MyniQ',
        url: 'https://daily-ai-generated-quiz.deno.dev/?from=corp',
        description:
          'AIが生成する英語の短文と読解力テストが毎日出題されます。代表がLLMの習作として作成したサービスです',
      },
    ],
  },
  en: {
    title: 'News & Links',
    description: 'Links and information related to our business',
    externalLink: 'External Link',
    entries: [
      {
        title: 'MyniQ',
        url: 'https://daily-ai-generated-quiz.deno.dev/?from=corp',
        description:
          'Daily English short sentences and comprehension tests generated by AI. A service created by our CEO as a practice project using LLM',
      },
    ],
  },
}

export default function Other(): ReactElement {
  const { lang } = useLanguage()
  const t = texts[lang]

  return (
    <>
      <HeadLine id="other">{t.title}</HeadLine>
      <div className="mt-10 mx-auto">
        <p>{t.description}</p>
      </div>
      <div className="mt-10 mx-auto">
        <ul className="pl-2">
          {t.entries.map((entry, index) => (
            <a key={index} href={entry.url} target={'_blank'}>
              <dl className="flex flex-row">
                <dt className="text-lg w-16">{entry.title}</dt>
                <dd className="px-2">
                  <p className="underline">
                    {entry.url}
                    <span
                      title={t.externalLink}
                      className="inline-block align-sub bg-[url(/img/icons/link.svg)] bg-no-repeat w-3 h-3 ml-1"
                    />
                  </p>
                  <p className="mt-2">{entry.description}</p>
                </dd>
              </dl>
            </a>
          ))}
        </ul>
      </div>
    </>
  )
}
